  services:
    
    raft_1:
      image: "raft"
      hostname: "raft_1"
      networks:
        - "nats-network"
      deploy:
        resources:
          limits:
            cpus: '0.1'
            memory: 7M
          reservations:
            cpus: '0.05'
            memory: 6M
      depends_on:
        - "nats"
    raft_2:
      image: "raft"
      hostname: "raft_2"
      networks:
        - "nats-network"
      deploy:
        resources:
          limits:
            cpus: '0.1'
            memory: 7M
          reservations:
            cpus: '0.05'
            memory: 6M
      depends_on:
        - "raft_1"
    raft_3:
      image: "raft"
      hostname: "raft_3"
      networks:
        - "nats-network"
      deploy:
        resources:
          limits:
            cpus: '0.1'
            memory: 7M
          reservations:
            cpus: '0.05'
            memory: 6M
      depends_on:
        - "raft_2"
    raft_4:
      image: "raft"
      hostname: "raft_4"
      networks:
        - "nats-network"
      deploy:
        resources:
          limits:
            cpus: '0.1'
            memory: 7M
          reservations:
            cpus: '0.05'
            memory: 6M
      depends_on:
        - "raft_3"
    raft_5:
      image: "raft"
      hostname: "raft_5"
      networks:
        - "nats-network"
      deploy:
        resources:
          limits:
            cpus: '0.1'
            memory: 7M
          reservations:
            cpus: '0.05'
            memory: 6M
      depends_on:
        - "raft_4"
    nats:
      image: "nats:latest"
      hostname: "nats-server"
      expose:
        - "8222"
      ports:
        - "8222:8222"
      networks:
        - "nats-network"
      command: "--cluster_name nat-cluster --cluster nats://0.0.0.0:6222 --http_port 8222 "
      deploy:
        resources:
          limits:
            cpus: '0.1'
            memory: 7M
          reservations:
            cpus: '0.05'
            memory: 6M
    nats-1:
      image: "nats:latest"
      hostname: "nats-server-1"
      networks:
        - "nats-network"
      command: "--cluster_name nat-cluster --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
      deploy:
        resources:
          limits:
            cpus: '0.1'
            memory: 7M
          reservations:
            cpus: '0.05'
            memory: 6M
      depends_on:
        - "nats"
    

  networks:
    nats-network:
      driver: bridge

