  # volumes:
  #   raft_logs:
  #     name: raft_logs

# =======================
  networks:
    nats-network:
      driver: bridge
  
# =======================
  # volumes:
  #   # - type: bind
  #   #   source: /data/workspaces/go/github.com/foadmom/RAFT/logs
  #   #   target: /logs
  #   #   read_only: false  
  #   logs: 
  #     external: true
      
      
# =======================
# =======================
  services:
# =======================
    raft_1:
      image: "raft:latest"
      # volumes:
      #   - /data/workspaces/go/github.com/foadmom/RAFT/logs:/logs:rw
      # command: bash -c "/app/RAFT >> /data/workspaces/go/github.com/foadmom/RAFT/logs/raft.log 2>&1"
      networks:
        - "nats-network"
      deploy:
        mode: replicated
        replicas: 5
        resources:
          limits:
            cpus: '0.1'
            memory: 7M
          reservations:
            cpus: '0.05'
            memory: 6M
      depends_on:
        - "nats"

      
# =======================
    # raft_2:
    #   image: "raft:latest"
    #   hostname: "raft_2"
    #   networks:
    #     - "nats-network"
    #   deploy:
    #     resources:
    #       limits:
    #         cpus: '0.1'
    #         memory: 7M
    #       reservations:
    #         cpus: '0.05'
    #         memory: 6M
    #   depends_on:
    #     - "nats"
    #
# =======================
    # raft_3:
    #   image: "raft:latest"
    #   hostname: "raft_3"
    #   networks:
    #     - "nats-network"
    #   deploy:
    #     resources:
    #       limits:
    #         cpus: '0.1'
    #         memory: 7M
    #       reservations:
    #         cpus: '0.05'
    #         memory: 6M
    #   depends_on:
    #     - "nats"
    #
# =======================
    # raft_4:
    #   image: "raft:latest"
    #   hostname: "raft_4"
    #   networks:
    #     - "nats-network"
    #   deploy:
    #     resources:
    #       limits:
    #         cpus: '0.1'
    #         memory: 7M
    #       reservations:
    #         cpus: '0.05'
    #         memory: 6M
    #   depends_on:
    #     - "nats"
    #
# =======================
    # raft_5:
    #   image: "raft:latest"
    #   hostname: "raft_5"
    #   networks:
    #     - "nats-network"
    #   deploy:
    #     resources:
    #       limits:
    #         cpus: '0.1'
    #         memory: 7M
    #       reservations:
    #         cpus: '0.05'
    #         memory: 6M
    #   depends_on:
    #     - "nats"
    #
# =======================
# =======================
# =======================
# nats cluster with 2 nodes.
# =======================
# =======================
# =======================
    nats:
      image: "nats:latest"
      hostname: "nats-server"
      expose:
        - "8222"
      ports:
        - "8222:8222"
      networks:
        - "nats-network"
      command: "--cluster_name nat-cluster --cluster nats://0.0.0.0:6222 --http_port 8222 "
      deploy:
        resources:
          limits:
            cpus: '0.1'
            memory: 10M
          reservations:
            cpus: '0.05'
            memory: 6M
# =======================
    nats-1:
      image: "nats:latest"
      hostname: "nats-server-1"
      networks:
        - "nats-network"
      command: "--cluster_name nat-cluster --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
      deploy:
        resources:
          limits:
            cpus: '0.1'
            memory: 10M
          reservations:
            cpus: '0.05'
            memory: 6M
      depends_on:
        - "nats"
    


